BEGIN;

-- Users table
CREATE TABLE IF NOT EXISTS "${PG_NAME}".users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Posts table
CREATE TABLE IF NOT EXISTS "${PG_NAME}".posts (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES "${PG_NAME}".users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Comments table
CREATE TABLE IF NOT EXISTS "${PG_NAME}".comments (
    id SERIAL PRIMARY KEY,
    post_id INTEGER REFERENCES "${PG_NAME}".posts(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES "${PG_NAME}".users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Grant privileges to PG_USER
GRANT ALL PRIVILEGES ON TABLE "${PG_NAME}".users TO "${PG_USER}";
GRANT ALL PRIVILEGES ON TABLE "${PG_NAME}".posts TO "${PG_USER}";
GRANT ALL PRIVILEGES ON TABLE "${PG_NAME}".comments TO "${PG_USER}";
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "${PG_USER}";

COMMIT;
